### ISSUE TITLE
fatal: A branch named 'master' already exists.

### ISSUE THREAD

**Issue by lpanebr** [ThePrimeagen/git-worktree.nvim#83]
This works to checkout my remote "master" branch in the "feat-69" path:
```lua
-- Creates a worktree.  Requires the path, branch name, and the upstream
-- Example:
:lua require("git-worktree").create_worktree("feat-69", "master", "origin")
```

But if I try:
```lua
:lua require("git-worktree").create_worktree("otherpath", "master", "origin")
```
to checkout the same "master" branch under "otherpath" I get this error:
`fatal: A branch named 'master' already exists.`

**What am I doing wrong?**

**Comment by TamaMcGlinn** [comment]
This is just a git feature - each branch can only be checked out in one place. It doesn't really make much sense when using worktrees, but this issue is upstream; try 'git worktree add some_branch_name' twice and you get the same error message. You should specify a new branchname. Easiest way is to [bind to the add command like it says in the readme](https://github.com/ThePrimeagen/git-worktree.nvim#create-a-worktree).
